export enum TrackType {
  'EVENT_NETWORKEVENT',
  'EVENT_SCROLL',
  'EVENT_RESIZE',

  'UIEVENT_SELECT',

  'KEYBOARDEVENT_KEYDOWN',
  
  'MOUSEEVENT_CLICK',

  'TOUCHEVENT_TOUCHSTART',
  'TOUCHEVENT_TOUCHMOVE',
  'TOUCHEVENT_TOUCHEND',
  'TOUCHEVENT_TOUCHCANCEL',

  'FOCUSEVENT_FOCUSIN',
  'FOCUSEVENT_FOCUSOUT',

  'POINTEREVENT_POINTERMOVE',

  'STATECHANGE',
  'MUTATION',
  'XHRINTERCEPT',
  'ERROR',

  'EVENT_SELECTIONSTART',
  'EVENT_SELECTIONCHANGE',

  'INPUTEVENT_INPUT'
}